apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Values.secret.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secret.dockerconfigjson  }}
